//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Account.rc
//
#define IDC_DEL                         3
#define IDC_MONTH                       3
#define IDC_GETPAY_INTO_ACCOUNT         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ACCOUNT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN                       129
#define IDD_USER_ACCOUNT                130
#define IDB_TAB                         130
#define IDD_ACCOUNT_LOG                 131
#define IDD_INANDOUT                    132
#define IDD_REPORT                      133
#define IDD_SETTING                     134
#define IDD_DATA_MANAGE                 135
#define IDB_COMPANY_ACCOUNT             138
#define IDB_COMPANY_ACCOUNT2            139
#define IDB_COMPANY_ACCOUNT3            140
#define IDB_MONEY_IN                    142
#define IDB_MONEY_OUT                   143
#define IDB_MONEY_DRAW                  144
#define IDB_BACKUP                      145
#define IDB_BLUE_NEW                    146
#define IDB_BLUE_DEL                    147
#define IDB_BLUE_EDIT                   148
#define IDB_FIND                        149
#define IDB_RED_NEW                     150
#define IDB_PRINT                       151
#define IDB_RED_DEL                     152
#define IDB_RED_EDIT                    153
#define IDB_BANK                        154
#define IDB_HOME                        155
#define IDB_LOAD                        156
#define IDB_MAKEREPORT                  157
#define IDB_LOCK                        158
#define IDB_DELETE                      159
#define IDB_EXCEL                       160
#define IDB_EDIT                        161
#define IDB_CANCEL                      162
#define IDB_KEY                         163
#define IDB_ACCOUNT                     165
#define IDB_NO                          168
#define IDB_DELETE1                     177
#define IDB_PREV                        178
#define IDB_NEXT                        179
#define IDB_EMPTY_ACCOUNT               180
#define IDD_ACCOUNT_MANAGE              181
#define IDD_ACCOUNT_SEL                 182
#define IDD_ACCOUNT                     183
#define IDD_MONEY                       185
#define IDB_EDIT_DRAW                   186
#define IDB_EDIT_GET2                   188
#define IDB_EDIT_PAY2                   189
#define IDB_EDIT_PAY                    190
#define IDB_NEW_DRAW                    191
#define IDB_NEW_GET2                    192
#define IDB_NEW_GET                     193
#define IDB_NEW_PAY2                    194
#define IDB_NEW_PAY                     195
#define IDB_EDIT_GET                    196
#define IDD_MONEY_MOVE                  197
#define IDD_PAY                         198
#define IDD_INTO_ACCOUNT                199
#define IDB_TWOSIDE                     201
#define IDB_OK                          202
#define IDB_HELP                        206
#define IDD_SEARCH                      207
#define IDD_MAKE_REPORT                 208
#define IDB_ARROW                       209
#define IDC_ACCOUNT_SCOPE               1000
#define IDC_SEL_DATE                    1003
#define IDC_INCOME                      1004
#define IDC_OUTCOME                     1005
#define IDC_BANLANCE                    1006
#define IDC_BACKUP                      1007
#define IDC_CUR_USER                    1008
#define IDC_TAB1                        1009
#define IDC_PASSWORD                    1011
#define IDC_TAB                         1012
#define IDC_MAKE_REPORT                 1013
#define IDC_MAKE_EXCEL                  1014
#define IDC_LIST1                       1015
#define IDC_SEARCHIN                    1016
#define IDC_ADDIN                       1017
#define IDC_MODIFYIN                    1018
#define IDC_DELIN                       1019
#define IDC_LIST_OUT                    1020
#define IDC_SEARCHOUT                   1021
#define IDC_ADDOUT                      1022
#define IDC_MODIFYOUT                   1023
#define IDC_DELOUT                      1024
#define IDC_LIST_IN                     1025
#define IDC_LOGIN                       1026
#define IDC_RESTORE                     1028
#define IDC_COMBO_USERS                 1028
#define IDC_USER_PASSWORD               1029
#define IDC_MODIFY                      1030
#define IDC_CUSTOMER_LIST               1033
#define IDC_OWNER_LIST                  1034
#define IDC_INCOME_TYPE                 1035
#define IDC_PAY_TYPE                    1036
#define IDC_PAY_ITEM_TYPE               1037
#define IDC_PREV_PAGE                   1038
#define IDC_ADD_USER                    1039
#define IDC_NEXT_PAGE                   1040
#define IDC_TOTAL_MONEY                 1041
#define IDC_USERNAME                    1042
#define IDC_PREV_DATE                   1043
#define IDC_NEXT_DATE                   1044
#define IDC_RADIO_BANK                  1044
#define IDC_RADIO_MONEY                 1045
#define IDC_ACCOUNT_NAME                1046
#define IDC_MONEY_BASE                  1047
#define IDC_BUTTON_ACCOUNT              1047
#define IDC_BUTTON_ACCOUNT3             1048
#define IDC_BUTTON_ACCOUNT2             1049
#define IDC_ACCOUNT_LEFT                1049
#define IDC_BALANCE                     1050
#define IDC_NUMBER                      1050
#define IDC_CUSTOMER_NAME               1052
#define IDC_SAVE                        1053
#define IDC_INPUT_TIME                  1054
#define IDC_MONEY                       1055
#define IDC_OWNER                       1057
#define IDC_REMARK                      1060
#define IDC_TYPE                        1061
#define IDC_EDIT                        1062
#define IDC_TODAY_INCOME                1064
#define IDC_TODAY_OUTCOME               1065
#define IDC_LASTDAY_LEFT                1066
#define IDC_TODAY_LEFT                  1067
#define IDC_ACCOUNT1                    1068
#define IDC_ACCOUNT2                    1069
#define IDC_TIME                        1071
#define IDC_CUSTOMER                    1074
#define IDC_GET_MONEY                   1075
#define IDC_GETTED_MONEY                1076
#define IDC_LEFT_MONEY                  1077
#define IDC_SAVE_CUSTOMER               1079
#define IDC_STATIC_GETPAY               1080
#define IDC_STATIC_GETTED_PAY           1081
#define IDC_MODIFY_ACCOUNT              1082
#define IDC_PIC                         1083
#define IDC_TIME1                       1085
#define IDC_TIME2                       1086
#define IDC_COMBO_TYPE                  1089
#define IDC_MONEY1                      1093
#define IDC_MONEY2                      1094
#define IDC_CHECK_TIME                  1095
#define IDC_CHECK_MONEY                 1096
#define IDC_COMBO_CUSTOMER              1097
#define IDC_COMBO_INCOME_TYPE           1098
#define IDC_COMBO_PAY_TYPE              1099
#define IDC_COMBO_PAY_ITEM_TYPE         1100
#define IDC_COMBO_OWNER                 1101
#define IDC_LIST_ACCOUNT                1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
